services:
  apache:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80

  mysql:
    image: mysql:debian
    command: --default-authentication-plugin=mysql_native_password --skip-log-bin
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
