services:
  apache:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80

  mysql:
    image: mariadb:11.3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
